version: '4.0'

actions:
             
  generate_dataset_incidence:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_incidence.py --output output/dataset_incidence.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_incidence.csv 

  generate_dataset_eia:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_eia.py --output output/dataset_eia.csv
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        cohort: output/dataset_eia.csv       

  generate_measures_2016:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2016.csv
      --
      --start-date "2016-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2016.csv

  generate_measures_2017:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2017.csv
      --
      --start-date "2017-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2017.csv             

  generate_measures_2018:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2018.csv
      --
      --start-date "2018-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2018.csv

  generate_measures_2019:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2019.csv
      --
      --start-date "2019-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2019.csv

  generate_measures_2020:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2020.csv
      --
      --start-date "2020-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2020.csv

  generate_measures_2021:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2021.csv
      --
      --start-date "2021-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2021.csv

  generate_measures_2022:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2022.csv
      --
      --start-date "2022-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2022.csv

  generate_measures_2023:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2023.csv
      --
      --start-date "2023-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2023.csv

  generate_measures_2024:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_incidence_2024.csv
      --
      --start-date "2024-04-01"
      --intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_incidence_2024.csv

  incidence_disease:
    run: stata-mp:latest analysis/001_disease_incidence.do
    needs: [generate_dataset_incidence, generate_measures_2016, generate_measures_2017, generate_measures_2018, generate_measures_2019, generate_measures_2020, generate_measures_2021, generate_measures_2022, generate_measures_2023, generate_measures_2024]
    outputs:
      moderately_sensitive:
        log1: logs/incidence_disease.log   
        table1: output/tables/baseline_table_rounded.csv
        table2: output/tables/incidence_count_*.csv
        table3: output/tables/incidence_count_p_*.csv
        table4: output/tables/incidence_rates_rounded.csv
        figure1: output/figures/count_inc_*.svg      
        figure2: output/figures/count_inc_p_*.svg
        figure3: output/figures/inc_rate_*.svg

  run_sarima:
    run: r:latest analysis/200_sarima.R
    needs: [incidence_disease]
    outputs:
      moderately_sensitive:
        log1: logs/sarima_log.txt   
        figure1: output/figures/raw_pre_covid_*.svg
        figure2: output/figures/differenced_pre_covid_*.svg
        figure3: output/figures/seasonal_pre_covid_*.svg
        figure4: output/figures/raw_acf_*.svg
        figure5: output/figures/differenced_acf_*.svg
        figure6: output/figures/seasonal_acf_*.svg
        figure7: output/figures/auto_residuals_*.svg
        figure8: output/figures/obs_pred_*.svg
        table1: output/tables/change_incidence_byyear.csv
        table2: output/tables/values_*.csv

  eia_cleaning:
    run: stata-mp:latest analysis/100_eia_cleaning.do
    needs: [generate_dataset_incidence, generate_dataset_eia]
    outputs:
      highly_sensitive:
        log1: logs/eia_dataset.log   
        data1: output/data/file_eia_all.dta  