
version: '4.0'

actions:    
  generate_dataset_incidence:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_incidence.py
      --output output/dataset_incidence.csv
      --
      --studystart_date "2016-04-01"
      --studyend_date "2025-03-31"
      --studyfup_date "2026-03-31"
      --diseases_list eia rheumatoid psa axialspa undiffia gca sjogren ssc sle myositis anca
      --registration_months 12
    outputs:
      highly_sensitive:
        cohort: output/dataset_incidence.csv

  generate_dataset_incidence_ref:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_incidence_ref.py 
      --output output/dataset_incidence_ref.csv
      --
      --studystart_date "2016-04-01"
      --studyend_date "2025-03-31"
    outputs:
      highly_sensitive:
        cohort: output/dataset_incidence_ref.csv

  reference_cleaning:
    run: stata-mp:latest analysis/003_reference_cleaning.do
    needs: [generate_dataset_incidence_ref]
    outputs:
      moderately_sensitive:
        log1: logs/reference_cleaning.log   
        table1: output/tables/reference_table_rounded.csv        

  generate_dataset_gca:
      run: ehrql:v1 generate-dataset analysis/dataset_definition_gca.py 
        --output output/dataset_gca.csv
        --
        --studystart_date "2016-04-01"
        --studyend_date "2025-03-31"
        --studyfup_date "2026-03-31"
        --diseases_list eia rheumatoid psa axialspa undiffia gca sjogren ssc sle myositis anca
        --registration_months 12
      needs: [generate_dataset_incidence]
      outputs:
        highly_sensitive:
          cohort: output/dataset_gca.csv

  gca_cleaning:
    run: stata-mp:latest analysis/101_gca_cleaning.do "2016-04-01" "2025-03-31" "2026-03-31"
    needs: [generate_dataset_gca]
    outputs:
      highly_sensitive:
        log1: logs/gca_cleaning.log   
        data1: output/data/gca_processed.dta

  gca_datatables:
    run: stata-mp:latest analysis/201_gca_datatables.do "2016-04-01" "2025-03-31" "2026-03-31"
    needs: [gca_cleaning]
    outputs:
      moderately_sensitive:
        log1: logs/gca_datatables.log   
        table1: output/tables/gca_datatable_*.csv

  gca_temporal_plots:
    run: stata-mp:latest analysis/301_gca_plots.do "2016-04-01" "2025-03-31" "2026-03-31" "2020-03-01"
    needs: [gca_datatables]
    outputs:
      moderately_sensitive:
        log1: logs/gca_plots.log   
        figure1: output/figures/gca_plot_*.svg                                                            
